// <auto-generated />
namespace KarateKlub.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class izmjenaTabelaUpisnine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(izmjenaTabelaUpisnine));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181031055_izmjenaTabelaUpisnine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
